name: Nano Unit Tests For OnnxRuntime

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test-nano-test-code ]
  pull_request:
    branches: [ main ]
    paths:
      - 'python/nano/**'
      - '.github/workflows/nano_onnx_tests.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nano-onnx-pytorch-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.7"]
        pytorch-version: [
          "torch==1.11.0+cpu torchvision==0.12.0+cpu",
          "torch==1.10.1+cpu torchvision==0.11.2+cpu",
          ""
          ]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Run onnx PyTorch unit tests
        shell: bash
        run: |
          $CONDA/bin/conda create -n onnx-pytorch -y python==3.7.10 setuptools=58.0.4
          source $CONDA/bin/activate onnx-pytorch
          $CONDA/bin/conda info
          bash python/nano/dev/build_and_install.sh linux default false pytorch
          if [ ! -z "${{matrix.pytorch-version}}" ]; then
            pip install ${{matrix.pytorch-version}} -f https://download.pytorch.org/whl/torch_stable.html
          fi
          pip install pytest
          pip install neural-compressor==1.11
          pip install onnxruntime onnxruntime-extensions onnx
          source bigdl-nano-init
          bash python/nano/test/run-nano-pytorch-onnx-tests.sh
          source $CONDA/bin/deactivate
          $CONDA/bin/conda remove -n onnx-pytorch --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
