name: code style checking

# Controls when the action will run.
on:
  push:
    branches: [ test-nano-test-code ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  style-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install pycodestyle
             pip install pydocstyle
             pip install mypy
             pip install wheel

      # Runs a single command using the runners shell
      - name: License checking
        run: bash python/dev/check-license

      - name: Nano style checking
        run: |
            bash python/nano/test/run-nano-codestyle-test.sh
        env:
            ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Nano type checking [pytorch]
        run: |
            bash python/nano/dev/build_and_install.sh linux default false pytorch
            pip uninstall bigdl-nano -y
            rm -rf python/nano/src/build python/nano/src/dist python/nano/src/*egg-info
            bash python/nano/test/run-nano-type-test.sh
        env:
            ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Nano type checking [tensorflow]
        run: |
            bash python/nano/dev/build_and_install.sh linux default false tensorflow
            pip uninstall bigdl-nano -y
            rm -rf python/nano/src/build python/nano/src/dist python/nano/src/*egg-info
            bash python/nano/test/run-nano-type-test.sh
        env:
            ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Dllib style checking
        run: bash python/dllib/dev/lint-python

      - name: Orca style checking
        run: bash python/orca/dev/test/lint-python

      - name: Friesian style checking
        run: bash python/friesian/dev/test/lint-python

      - name: Chronos style checking
        run: bash python/chronos/dev/test/lint-python

      - name: Nano style checking
        run: bash python/nano/dev/lint-python

      - name: Serving style checking
        run: bash python/serving/dev/lint-python
